version: '3'

services:
  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 3030:3030
  frontend:
    container_name: frontend
    depends_on:
      - backend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - 3000:80
